### ISSUE TITLE
What modification have you made to this addon?

### ISSUE THREAD

**Issue by luzpaz** [SuzanneSoy/SearchBar#1]
Hi! Just wondering. The original dev has stepped away from the FreeCAD. I'd love to see this as part of FreeCAD core

**Comment by luzpaz** [comment]
bump @SuzanneSoy

**Comment by SuzanneSoy** [comment]
Sorry aout that, I am the original dev and this is the original version of this addon. I'll try to make improvements based on the feedback I got on the forum https://forum.freecadweb.org/viewtopic.php?f=22&t=62974 when I find some time & energy to work on this again :)

**Comment by luzpaz** [comment]
@SuzanneSoy thanks. There is another addon called [Launcher](https://github.com/triplus/Launcher). how does this differ from that?

**Comment by SuzanneSoy** [comment]
* Launcher uses a `QtGui.QDockWidget`, whereas SearchBar just adds the search bar in the file menu, next to the "What's This?" button. I should give `QtGui.QDockWidget` a try, seems like a much better solution.

**Comment by SuzanneSoy** [comment]
Sure, in a couple of days? I'll try to address some of the most pressing issues (like saying in the README that FreeCAD's 3D view widget is unstable and can crash the entire app).

**Comment by chennes** [comment]
> I'm not sure how the update process goes with the addon manager, do I need to submit an MR to the addon manager repo every time I make updates to this repo?

No, we just add it as a submodule, nothing changes about your development process.

**Comment by luzpaz** [comment]
Sorry, forgot to mention that. Thanks chennes.

**Comment by SuzanneSoy** [comment]
> > I'm not sure how the update process goes with the addon manager, do I need to submit an MR to the addon manager repo every time I make updates to this repo?
> 
> No, we just add it as a submodule, nothing changes about your development process.

:thinking: submodules are normally pinned to a specific commit?

I'm working through my to-do list, should be good for release soon.

**Comment by luzpaz** [comment]
@SuzanneSoy any progress on this? FreeCAD is going to announce a release soon. There is [feature freeze starting March 4th](https://forum.freecadweb.org/viewtopic.php?f=10&t=66407) but this doesn't apply to 3rd party addons. Nevertheless, it would be amazing if this addon could be stable for the upcoming release where we'll see an influx of users testing out the new version and most likely this addon would get exposure (esp. for newbs)

**Comment by SuzanneSoy** [comment]
@luzpaz  Yes! I just finished implementing the "enable 3D preview" button tonight, so it shouldn't cause crashes until enabled :)

I think it's now good enough to enable in the public addon repo.

Do I need to do anything / submit an MR for that?

Thanks for your patience!

**Comment by luzpaz** [comment]
@SuzanneSoy I can add it the Addon Manager. But there are other things left to do in this repo:
- [ ] Add [`package.xml`](https://wiki.freecadweb.org/Package_Metadata#Examples)  
- [ ] Announce on the forum. This is a thread the community can use to report bugs, ask for features, submit patches to
- [ ] Add a section in the README for the forum link (mentioned above) + mention is the issue quese for tracking bugs/features
- [ ] Add a section on Automatic Install and mention Addon Manager

**Comment by SuzanneSoy** [comment]
The announcement on the forum was already done a while ago: https://forum.freecadweb.org/viewtopic.php?f=22&t=62974 should I make a new thread? There haven't been any significant changes since then, just small bugfixes and tweaks.

**Comment by SuzanneSoy** [comment]
I turn any points left in https://forum.freecadweb.org/viewtopic.php?f=22&t=62974 into issues on this repo, closing this now as this was just a reminder for me to have a look at the forum thread. :)
