### ISSUE TITLE
Discussion for using SearchBar-esque approach for the FreeCAD Preference panel

### ISSUE THREAD

**Issue by luzpaz** [SuzanneSoy/SearchBar#13]
https://forum.freecadweb.org/viewtopic.php?p=587777#p587777

Though it could be useful to x-post. Maybe it could augment SearchBar methodology so that we could manipulate preferences directly from searchbar, eventually?

**Comment by SuzanneSoy** [comment]
Closing this as a duplicate of https://github.com/SuzanneSoy/SearchBar/issues/23
