### ISSUE TITLE
Perhaps this addon needs a new maintainer ?

### ISSUE THREAD

**Issue by luzpaz** [SuzanneSoy/SearchBar#35]
@SuzanneSoy would you be OK with someone forking and taking over maintaining this addon?

**Comment by hasecilu** [comment]
Trying to use, integrated on Ribbon get all this errors.

![image](https://github.com/user-attachments/assets/2d823647-c964-4359-a0e1-b2f759ef3db2)

**Comment by luzpaz** [comment]
@hasecilu see 
* https://github.com/APEbbers/FreeCAD-Ribbon/issues/56#issuecomment-2464910641

**Comment by luzpaz** [comment]
Maintainership has changed  
* https://github.com/FreeCAD/FreeCAD-addons/issues/330

Thanks for all your work @SuzanneSoy
