### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by luzpaz** [SuzanneSoy/SearchBar#5]
Address issues of https://github.com/SuzanneSoy/SearchBar/issues/1#issuecomment-1055626952 in PR #3

![image](https://user-images.githubusercontent.com/4140247/156215976-5dfadb0c-cac4-44b2-8ad4-b67462a5f7fa.png) (this image is used on the README page. Please don't delete it from this ticket.)

**Comment by SuzanneSoy** [comment]
PR merged, thanks a lot :)
